Included arduino source and started modifying build scripts to use an include directory in the build environment.  Everything is still horribly broken but I'm going to the Lions game right now.

diff --git a/scripts/build_pde b/scripts/build_pde
--- a/scripts/build_pde
+++ b/scripts/build_pde
@@ -26,40 +26,42 @@
 PDE_FILE=$1
 PROGRAM=${PDE_FILE%.pde}
 
-# Set up file paths.
-prefix=`pwd`/test
+# Make sure we have a file to compile.
+if [ "${PROGRAM}" = "" ] ; then
+   echo
+   echo Usage: `basename $0` \<filename.pde\>
+   echo
+   exit 1
+fi
+
+# These should be the default directories where the libarduino
+# package will get installed to.  The paths here need to be turned
+# into autotools paths.
+#
+#prefix=/usr/local
+#exec_prefix=${prefix}
+#libdir=${exec_prefix}/lib
+#localstatedir=${prefix}/var/lib/libarduino
+#datarootdir=${prefix}/share/libarduino
+#datadir=${datarootdir}/libarduino
+
+prefix=.
 exec_prefix=${prefix}
-libdir=${exec_prefix}/lib
-localstatedir=${prefix}/build/${PROGRAM}
-datarootdir=..
-datadir=${datarootdir}/data
-srcdir=${prefix}/src/${PROGRAM}
+libdir=../lib
+localstatedir=./test
+datarootdir=../data
+datadir=${datarootdir}
+
+# Set up file paths for building arduino libs and apps.
+arduino_prefix=${localstatedir}
+arduino_libdir=${arduino_prefix}/lib
+arduino_includedir=${arduinoprefix}/include
+arduino_localstatedir=${arduino_prefix}/build/${PROGRAM}
+arduino_srcdir=${arduino_prefix}/src/${PROGRAM}
 
 
-########
-# functions
-########
-
-# This figures out the absolute path of any give path.
-abspath () {
-   dir=$1
-
-   # Basically, if the path begins with a '/', it's absolute.  Otherwise,
-   # it's relative so tack on the pwd results.
-   case $dir in
-      /*) echo $1 ;;
-      *) echo `pwd`/$1 ;;
-   esac
-} /* abspath */
-
-
-# This function pulls out all the relative headers in a c/c++/pde file.
-relhdrs () {
-   srcfile=$1
-
-   grep "^#include" $srcfile | cut -d\" -f2 -s
-} /* relhdrs */
-
+# Include some useful functions.
+. ${libdir}/init-functions
 
 
 #######
@@ -69,34 +71,35 @@ relhdrs () {
 ##### Set up the program sources #####
 
 # Make the source directory and add a symlink to the pde file.
-mkdir -p ${srcdir}
-cp ${datadir}/main.c ${srcdir}
-ln -s `abspath $PDE_FILE` ${srcdir}/arduino_program.pde
+mkdir -p $arduino_srcdir
+cp ${datadir}/main.c $arduino_srcdir
+ln -f -s `abspath $PDE_FILE` ${arduino_srcdir}/arduino_program.pde
 
 # Scan the pde file for relative headers and make symlinks
 # to the files in the src directory so it compiles properly.
-for file in `relhdrs $PDE_FILE` ; do 
-   ln -s `abspath $file` ${srcdir}
-done
+#for file in `relhdrs $PDE_FILE` ; do 
+#   ln -s `abspath $file` ${srcdir}
+#done
 
 
 ##### Set up the build directory #####
 
 # Create links to the files in the source directory.
-ln -s ${srcdir}/* $localstatedir
+mkdir -p $arduino_localstatedir
+ln -f -s ${arduinoo_srcdir}/* $arduino_localstatedir
 
 # Copy over the custom make file.
-cp ${datadir}/Makefile.pde ${localstatedir}/Makefile
+cp ${datadir}/Makefile.pde ${arduino_localstatedir}/Makefile
 
 
 ######### Make the program ########
 
 echo "Cross compiling..."
-make -C $localstatedir
+#make -C $arduino_localstatedir
 
 
 # Check to make sure it finished successfully.
-if [ -f ${localstatedir}/arduino_program.hex ];
+if [ -f ${arduino_localstatedir}/arduino_program.hex ];
 then
    echo
    echo "Success!!"
@@ -104,7 +107,7 @@ then
    exit 0
 else
    echo  
-   echo "Something broke - cannot find ${localstatedir}/arduino_program.hex."
+   echo "Something broke - cannot find ${arduino_localstatedir}/arduino_program.hex."
    echo
    exit 1
 fi
